steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['run', 'start']

  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'backend'
    args:
      [
        'run', 'deploy', 'moneyantra',
        '--source=.',
        '--region=us-central1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--set-secrets=drive.json=moneyantra-drive-json:latest'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
